
const elements = {
    '1': {
        'symbol': 'H',
        'atomicNumber': 1,
        'family': 1,
        'name': 'Hydrogen',
        "japaneseName": "水素",
        'radius': 0.53,
        'tableRow': 1,
        'tableColumn': 1,
        'spiralRow': 1,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '1s',
        'electron': {
            '1': { 's': 1 }
        },
        'atomicMass': 1.00794,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1312,
        'electronAffinity': 72.769,
        'meltingPoint': -259.16,
        'boilingPoint': -252.879,
        'state': 'gas',
        'density': 0.08988,
    },
    '2': {
        'symbol': 'He',
        'atomicNumber': 2,
        'family': 18,
        'name': 'Helium',
        "japaneseName": "ヘリウム",
        'radius': 0.31,
        'tableRow': 1,
        'tableColumn': 18,
        'spiralRow': 1,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '1s',
        'electron': {
            '1': { 's': 2 }
        },
        'atomicMass': 4.002602,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 2372.3,
        'electronAffinity': -48,
        'meltingPoint': -272.20,
        'boilingPoint': -268.928,
        'state': 'gas',
        'density': 0.1785,
    },

    '3': {
        'symbol': 'Li',
        'atomicNumber': 3,
        'family': 1,
        'name': 'Lithium',
        "japaneseName": "リチウム",
        'radius': 1.67,
        'tableRow': 2,
        'tableColumn': 1,
        'spiralRow': 1,
        'spiralColumn': 6,
        'winding': 1,
        'orbit': '2s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 1 }
        },
        'atomicMass': 6.941,
        'metallic': 'metal',
        '1stIonizationEnergy': 520.2,
        'electronAffinity': 59.632,
        'meltingPoint': 180.50,
        'boilingPoint': 1330,
        'state': 'solid',
        'density': 0.534,
    },
    '4': {
        'symbol': 'Be',
        'atomicNumber': 4,
        'family': 2,
        'name': 'Beryllium',
        "japaneseName": "ベリリウム",
        'radius': 1.12,
        'tableRow': 2,
        'tableColumn': 2,
        'spiralRow': 1,
        'spiralColumn': 7,
        'winding': 1,
        'orbit': '2s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2 }
        },
        'atomicMass': 9.012182,
        'metallic': 'metal',
        '1stIonizationEnergy': 899.5,
        'electronAffinity': -48,
        'meltingPoint': 1287,
        'boilingPoint': 2469,
        'state': 'solid',
        'density': 1.85,
    },
    '5': {
        'symbol': 'B',
        'atomicNumber': 5,
        'family': 13,
        'name': 'Boron',
        "japaneseName": "ホウ素",
        'radius': 0.87,
        'tableRow': 2,
        'tableColumn': 13,
        'spiralRow': 1,
        'spiralColumn': 8,
        'winding': 1,
        'orbit': '2p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 1 },
        },
        'atomicMass': 10.811,
        'metallic': 'semimetal',
        '1stIonizationEnergy': 800.6,
        'electronAffinity': 26.986,
        'meltingPoint': 2076,
        'boilingPoint': 3927,
        'state': 'solid',
        'density': 2.34,
    },
    '6': {
        'symbol': 'C',
        'atomicNumber': 6,
        'family': 14,
        'name': 'Carbon',
        "japaneseName": "炭素",
        'radius': 0.67,
        'tableRow': 2,
        'tableColumn': 14,
        'spiralRow': 2,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '2p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 2 },
        },
        'atomicMass': 12.0107,
        'metallic': 'semimetal',
        '1stIonizationEnergy': 1086.5,
        'electronAffinity': 121.776,
        'meltingPoint': 3642, //昇華
        'boilingPoint': 3642,
        'state': 'solid',
        'density': 3.513
    },
    '7': {
        'symbol': 'N',
        'atomicNumber': 7,
        'family': 15,
        'name': 'Nitrogen',
        "japaneseName": "窒素",
        'radius': 0.56,
        'tableRow': 2,
        'tableColumn': 15,
        'spiralRow': 2,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '2p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 3 },
        },
        'atomicMass': 14.0067,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1402.3,
        'electronAffinity': -6.8,
        'meltingPoint': -209.86,
        'boilingPoint': -195.795,
        'state': 'gas',
        'density': 1.251,
    },
    '8': {
        'symbol': 'O',
        'atomicNumber': 8,
        'family': 16,
        'name': 'Oxygen',
        "japaneseName": "酸素",
        'radius': 0.48,
        'tableRow': 2,
        'tableColumn': 16,
        'spiralRow': 2,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '2p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 4 },
        },
        'atomicMass': 15.9994,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1313.9,
        'electronAffinity': 141,
        'meltingPoint': -218.79,
        'boilingPoint': -182.962,
        'state': 'gas',
        'density': 1.429,
    },
    '9': {
        'symbol': 'F',
        'atomicNumber': 9,
        'family': 17,
        'name': 'Fluorine',
        "japaneseName": "フッ素",
        'radius': 0.42,
        'tableRow': 2,
        'tableColumn': 17,
        'spiralRow': 2,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '2p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 5 },
        },
        'atomicMass': 18.9984032,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1681,
        'electronAffinity': 328.164,
        'meltingPoint': -219.67,
        'boilingPoint': -188.11,
        'state': 'gas',
        'density': 1.696,
    },
    '10': {
        'symbol': 'Ne',
        'atomicNumber': 10,
        'family': 18,
        'name': 'Neon',
        "japaneseName": "ネオン",
        'radius': 0.38,
        'tableRow': 2,
        'tableColumn': 18,
        'spiralRow': 2,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '2p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
        },
        'atomicMass': 20.1797,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 2080.7,
        'electronAffinity': -116,
        'meltingPoint': -248.59,
        'boilingPoint': -246.046,
        'state': 'gas',
        'density': 0.9002,
    },
    '11': {
        'symbol': 'Na',
        'atomicNumber': 11,
        'family': 1,
        'name': 'Sodium',
        "japaneseName": "ナトリウム",
        'radius': 1.90,
        'tableRow': 3,
        'tableColumn': 1,
        'spiralRow': 2,
        'spiralColumn': 6,
        'winding': 1,
        'orbit': '3s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 1 }
        },
        'atomicMass': 22.98976928,
        'metallic': 'metal',
        '1stIonizationEnergy': 495.8,
        'electronAffinity': 52.867,
        'meltingPoint': 97.794,
        'boilingPoint': 882.940,
        'state': 'solid',
        'density': 0.971,
    },
    '12': {
        'symbol': 'Mg',
        'atomicNumber': 12,
        'family': 2,
        'name': 'Magnesium',
        "japaneseName": "マグネシウム",
        'radius': 1.45,
        'tableRow': 3,
        'tableColumn': 2,
        'spiralRow': 2,
        'spiralColumn': 7,
        'winding': 1,
        'orbit': '3s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2 },
        },
        'atomicMass': 24.3050,
        'metallic': 'metal',
        '1stIonizationEnergy': 737.7,
        'electronAffinity': -40,
        'meltingPoint': 650,
        'boilingPoint': 1091,
        'state': 'solid',
        'density': 1.738,
    },
    '13': {
        'symbol': 'Al',
        'atomicNumber': 13,
        'family': 13,
        'name': 'Aluminum',
        "japaneseName": "アルミニウム",
        'radius': 1.18,
        'tableRow': 3,
        'tableColumn': 13,
        'spiralRow': 2,
        'spiralColumn': 8,
        'winding': 1,
        'orbit': '3p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 1 },
        },
        'atomicMass': 26.9815386,
        'metallic': 'metal',
        '1stIonizationEnergy': 577.5,
        'electronAffinity': 41.762,
        'meltingPoint': 660.32,
        'boilingPoint': 2470,
        'state': 'solid',
        'density': 2.70,
    },
    '14': {
        'symbol': 'Si',
        'atomicNumber': 14,
        'family': 14,
        'name': 'Silicon',
        "japaneseName": "ケイ素",
        'radius': 1.11,
        'tableRow': 3,
        'tableColumn': 14,
        'spiralRow': 3,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '3p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 2 },
        },
        'atomicMass': 28.0855,
        'metallic': 'semimetal',
        '1stIonizationEnergy': 786.5,
        'electronAffinity': 134.068,
        'meltingPoint': 1414,
        'boilingPoint': 3265,
        'state': 'solid',
        'density': 2.329,
    },
    '15': {
        'symbol': 'P',
        'atomicNumber': 15,
        'family': 15,
        'name': 'Phosphorus',
        "japaneseName": "リン",
        'radius': 0.98,
        'tableRow': 3,
        'tableColumn': 15,
        'spiralRow': 3,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '3p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 3 },
        },
        'atomicMass': 30.973762,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1011.8,
        'electronAffinity': 72.037,
        'meltingPoint': 44.15,
        'boilingPoint': 280.5,
        'state': 'solid',
        'density': 1.82,

    },
    '16': {
        'symbol': 'S',
        'atomicNumber': 16,
        'family': 16,
        'name': 'Sulfur',
        "japaneseName":     "硫黄",
        'radius': 0.88,
        'tableRow': 3,
        'tableColumn': 16,
        'spiralRow': 3,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '3p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 4 },
        },
        'atomicMass': 32.065,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 999.6,
        'electronAffinity': 200.410,
        'meltingPoint': 115.21,
        'boilingPoint': 444.6,
        'state': 'solid',
        'density': 2.067,
    },
    '17': {
        'symbol': 'Cl',
        'atomicNumber': 17,
        'family': 17,
        'name': 'Chlorine',
        "japaneseName": "塩素",
        'radius': 0.79,
        'tableRow': 3,
        'tableColumn': 17,
        'spiralRow': 3,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '3p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 5 },
        },
        'atomicMass': 35.453,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1251.2,
        'electronAffinity': 348.575,
        'meltingPoint': -101.5,
        'boilingPoint': -34.04,
        'state': 'gas',
        'density': 0.003214,
    },
    '18': {
        'symbol': 'Ar',
        'atomicNumber': 18,
        'family': 18,
        'name': 'Argon',
        "japaneseName": "アルゴン",
        'radius': 0.71,
        'tableRow': 3,
        'tableColumn': 18,
        'spiralRow': 3,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '3p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6 },
        },
        'atomicMass': 39.948,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1520.6,
        'electronAffinity': -96,
        'meltingPoint': -189.34,
        'boilingPoint': -185.848,
        'state': 'gas',
        'density': 0.001784,
    },
    '19': {
        'symbol': 'K',
        'atomicNumber': 19,
        'family': 1,
        'name': 'Potassium',
        "japaneseName": "カリウム",
        'radius': 2.43,
        'tableRow': 4,
        'tableColumn': 1,
        'spiralRow': 3,
        'spiralColumn': 6,
        'winding': 1,
        'orbit': '4s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6 },
            '4': { 's': 1 }
        },
        'atomicMass': 39.0983,
        'metallic': 'metal',
        '1stIonizationEnergy': 418.8,
        'electronAffinity': 48.383,
        'meltingPoint': 63.5,
        'boilingPoint': 757.643,
        'state': 'solid',
        'density': 0.856,
    },
    '20': {
        'symbol': 'Ca',
        'atomicNumber': 20,
        'family': 2,
        'name': 'Calcium',
        "japaneseName": "カルシウム",
        'radius': 1.94,
        'tableRow': 4,
        'tableColumn': 2,
        'spiralRow': 3,
        'spiralColumn': 7,
        'winding': 1,
        'orbit': '4s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6 },
            '4': { 's': 2 }
        },
        'atomicMass': 40.078,
        'metallic': 'metal',
        '1stIonizationEnergy': 589.8,
        'electronAffinity': 2.37,
        'meltingPoint': 842,
        'boilingPoint': 1484,
        'state': 'solid',
        'density': 1.55,
    },
    '21': {
        'symbol': 'Sc',
        'atomicNumber': 21,
        'family': 3,
        'name': 'Scandium',
        "japaneseName": "スカンジウム",
        'radius': 1.84,
        'tableRow': 4,
        'tableColumn': 3,
        'spiralRow': 3,
        'spiralColumn': 8,
        'winding': 1,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 1, 'p': 6, 'd': 1 },
            '4': { 's': 2 }
        },
        'atomicMass': 44.955912,
        'metallic': 'metal',
        '1stIonizationEnergy': 633.1,
        'electronAffinity': 17.307,
        'meltingPoint': 1541,
        'boilingPoint': 2836,
        'state': 'solid',
        'density': 2.985,
    },
    '22': {
        'symbol': 'Ti',
        'atomicNumber': 22,
        'family': 4,
        'name': 'Titanium',
        "japaneseName": "チタン",
        'radius': 1.76,
        'tableRow': 4,
        'tableColumn': 4,
        'spiralRow': 4,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 2 },
            '4': { 's': 2 }
        },
        'atomicMass': 47.867,
        'metallic': 'metal',
        '1stIonizationEnergy': 658.8,
        'electronAffinity': 7.289,
        'meltingPoint': 1668,
        'boilingPoint': 3287,
        'state': 'solid',
        'density': 4.507,
    },
    '23': {
        'symbol': 'V',
        'atomicNumber': 23,
        'family': 5,
        'name': 'Vanadium',
        "japaneseName": "バナジウム",
        'radius': 1.71,
        'tableRow': 4,
        'tableColumn': 5,
        'spiralRow': 4,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 3 },
            '4': { 's': 2 }
        },
        'atomicMass': 50.9415,
        'metallic': 'metal',
        '1stIonizationEnergy': 650.9,
        'electronAffinity': 50.911,
        'meltingPoint': 2183,
        'boilingPoint': 3407,
        'state': 'solid',
        'density': 6.0,
    },
    '24': {
        'symbol': 'Cr',
        'atomicNumber': 24,
        'family': 6,
        'name': 'Chromium',
        "japaneseName": "クロム",
        'radius': 1.66,
        'tableRow': 4,
        'tableColumn': 6,
        'spiralRow': 4,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 5 },
            '4': { 's': 1 }
        },
        'atomicMass': 51.9961,
        'metallic': 'metal',
        '1stIonizationEnergy': 652.9,
        'electronAffinity': 65.217,
        'meltingPoint': 1907,
        'boilingPoint': 2671,
        'state': 'solid',
        'density': 7.19,
    },
    '25': {
        'symbol': 'Mn',
        'atomicNumber': 25,
        'family': 7,
        'name': 'Manganese',
        "japaneseName": "マンガン",
        'radius': 1.61,
        'tableRow': 4,
        'tableColumn': 7,
        'spiralRow': 4,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 5 },
            '4': { 's': 2 }
        },
        'atomicMass': 54.938045,
        'metallic': 'metal',
        '1stIonizationEnergy': 717.3,
        'electronAffinity': -50,
        'meltingPoint': 1246,
        'boilingPoint': 2061,
        'state': 'solid',

    },
    '26': {
        'symbol': 'Fe',
        'atomicNumber': 26,
        'family': 8,
        'name': 'Iron',
        "japaneseName": "鉄",
        'radius': 1.56,
        'tableRow': 4,
        'tableColumn': 8,
        'spiralRow': 4,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 6 },
            '4': { 's': 2 }
        },
        'atomicMass': 55.845,
        'metallic': 'metal',
        '1stIonizationEnergy': 762.5,
        'electronAffinity': 14.785,
        'meltingPoint': 1538,
        'boilingPoint': 2861,
        'state': 'solid',
        'density': 7.874,
    },
    '27': {
        'symbol': 'Co',
        'atomicNumber': 27,
        'family': 9,
        'name': 'Cobalt',
        "japaneseName": "コバルト",
        'radius': 1.52,
        'tableRow': 4,
        'tableColumn': 9,
        'spiralRow': 4,
        'spiralColumn': 6,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 7 },
            '4': { 's': 2 }
        },
        'atomicMass': 58.933195,
        'metallic': 'metal',
        '1stIonizationEnergy': 760.4,
        'electronAffinity': 63.897,
        'meltingPoint': 1495,
        'boilingPoint': 2927,
        'state': 'solid',
        'density': 8.86,
    },
    '28': {
        'symbol': 'Ni',
        'atomicNumber': 28,
        'family': 10,
        'name': 'Nickel',
        "japaneseName": "ニッケル",
        'radius': 1.49,
        'tableRow': 4,
        'tableColumn': 10,
        'spiralRow': 4,
        'spiralColumn': 7,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 8 },
            '4': { 's': 2 }
        },
        'atomicMass': 58.6934,
        'metallic': 'metal',
        '1stIonizationEnergy': 737.1,
        'electronAffinity': 111.65,
        'meltingPoint': 1455,
        'boilingPoint': 2730,
        'state': 'solid',
        'density': 8.912,
    },
    '29': {
        'symbol': 'Cu',
        'atomicNumber': 29,
        'family': 11,
        'name': 'Copper',
        "japaneseName": "銅",
        'radius': 1.45,
        'tableRow': 4,
        'tableColumn': 11,
        'spiralRow': 4,
        'spiralColumn': 8,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 1 }
        },
        'atomicMass': 63.546,
        'metallic': 'metal',
        '1stIonizationEnergy': 745.5,
        'electronAffinity': 119.235,
        'meltingPoint': 1084.62,
        'boilingPoint': 2562,
        'state': 'solid',
        'density': 8.96,
    },
    '30': {
        'symbol': 'Zn',
        'atomicNumber': 30,
        'family': 12,
        'name': 'Zinc',
        "japaneseName": "亜鉛",
        'radius': 1.42,
        'tableRow': 4,
        'tableColumn': 12,
        'spiralRow': 4,
        'spiralColumn': 9,
        'winding': 0,
        'orbit': '3d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2 },
        },
        'atomicMass': 65.38,
        'metallic': 'metal',
        '1stIonizationEnergy': 906.4,
        'electronAffinity': -58,
        'meltingPoint': 419.53,
        'boilingPoint': 907,
        'state': 'solid',
        'density': 7.134,
    },
    '31': {
        'symbol': 'Ga',
        'atomicNumber': 31,
        'family': 13,
        'name': 'Gallium',
        "japaneseName": "ガリウム",
        'radius': 1.36,
        'tableRow': 4,
        'tableColumn': 13,
        'spiralRow': 4,
        'spiralColumn': 10,
        'winding': 1,
        'orbit': '4p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 1 },
        },
        'atomicMass': 69.723,
        'metallic': 'metal',
        '1stIonizationEnergy': 578.8,
        'electronAffinity': 28.058,
        'meltingPoint': 29.7646,
        'boilingPoint': 2403,
        'state': 'solid',
        'density': 5.907,
    },
    '32': {
        'symbol': 'Ge',
        'atomicNumber': 32,
        'family': 14,
        'name': 'Germanium',
        "japaneseName": "ゲルマニウム",
        'radius': 1.25,
        'tableRow': 4,
        'tableColumn': 14,
        'spiralRow': 5,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '4p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 2 },
        },
        'atomicMass': 72.64,
        'metallic': 'semimetal',
        '1stIonizationEnergy': 762,
        'electronAffinity': 118.935,
        'meltingPoint': 938.25,
        'boilingPoint': 2833,
        'state': 'solid',
        'density': 5.323,
    },
    '33': {
        'symbol': 'As',
        'atomicNumber': 33,
        'family': 15,
        'name': 'Arsenic',
        "japaneseName": "ヒ素",
        'radius': 1.14,
        'tableRow': 4,
        'tableColumn': 15,
        'spiralRow': 5,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '4p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 3 },
        },
        'atomicMass': 74.92160,
        'metallic': 'semimetal',
        '1stIonizationEnergy': 947,
        'electronAffinity': 77.65,
        'meltingPoint': 615,//sublime　昇華。
        'boilingPoint': 615,
        'state': 'solid',
        'density': 5.727,
    },
    '34': {
        'symbol': 'Se',
        'atomicNumber': 34,
        'family': 16,
        'name': 'Selenium',
        "japaneseName": "セレン",
        'radius': 1.03,
        'tableRow': 4,
        'tableColumn': 16,
        'spiralRow': 5,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '4p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 4 },
        },
        'atomicMass': 78.96,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 941,
        'electronAffinity': 194.958,
        'meltingPoint': 221,
        'boilingPoint': 685,
        'state': 'solid',
        'density': 4.809,
    },
    '35': {
        'symbol': 'Br',
        'atomicNumber': 35,
        'family': 17,
        'name': 'Bromine',
        "japaneseName": "臭素",
        'radius': 0.94,
        'tableRow': 4,
        'tableColumn': 17,
        'spiralRow': 5,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '4p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 5 },
        },
        'atomicMass': 79.904,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1139.9,
        'electronAffinity': 324.536,
        'meltingPoint': -7.2,
        'boilingPoint': 58.8,
        'state': 'liquid',
        'density': 3.122,
    },
    '36': {
        'symbol': 'Kr',
        'atomicNumber': 36,
        'family': 18,
        'name': 'Krypton',
        "japaneseName": "クリプトン",
        'radius': 0.88,
        'tableRow': 4,
        'tableColumn': 18,
        'spiralRow': 5,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '4p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6 },
        },
        'atomicMass': 83.798,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1350.8,
        'electronAffinity': -96,
        'meltingPoint': -157.37,
        'boilingPoint': -153.415,
        'state': 'gas',
        'density': 0.003733,
    },
    '37': {
        'symbol': 'Rb',
        'atomicNumber': 37,
        'family': 1,
        'name': 'Rubidium',
        "japaneseName": "ルビジウム",
        'radius': 2.65,
        'tableRow': 5,
        'tableColumn': 1,
        'spiralRow': 5,
        'spiralColumn': 6,
        'winding': 1,
        'orbit': '5s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6 },
            '5': { 's': 1 }
        },
        'atomicMass': 85.4678,
        'metallic': 'metal',
        '1stIonizationEnergy': 403,
        'electronAffinity': 46.884,
        'meltingPoint': 39.30,
        'boilingPoint': 688,
        'state': 'solid',
        'density': 1.532,
    },
    '38': {
        'symbol': 'Sr',
        'atomicNumber': 38,
        'family': 2,
        'name': 'Strontium',
        "japaneseName": "ストロンチウム",
        'radius': 2.19,
        'tableRow': 5,
        'tableColumn': 2,
        'spiralRow': 5,
        'spiralColumn': 7,
        'winding': 1,
        'orbit': '5s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6 },
            '5': { 's': 2 }
        },
        'atomicMass': 87.62,
        'metallic': 'metal',
        '1stIonizationEnergy': 549.5,
        'electronAffinity': 5.023,
        'meltingPoint': 777,
        'boilingPoint': 1377,
        'state': 'solid',
        'density': 2.64,
    },
    '39': {
        'symbol': 'Y',
        'atomicNumber': 39,
        'family': 3,
        'name': 'Yttrium',
        "japaneseName": "イットリウム",
        'radius': 2.12,
        'tableRow': 5,
        'tableColumn': 3,
        'spiralRow': 5,
        'spiralColumn': 8,
        'winding': 1,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 1},
            '5': { 's': 2 }
        },
        'atomicMass': 88.90585,
        'metallic': 'metal',
        '1stIonizationEnergy': 600,
        'electronAffinity': 30.035,
        'meltingPoint': 1526,
        'boilingPoint': 2930,
        'state': 'solid',
        'density': 4.472,
    },
    '40': {
        'symbol': 'Zr',
        'atomicNumber': 40,
        'family': 4,
        'name': 'Zirconium',
        "japaneseName": "ジルコニウム",
        'radius': 2.06,
        'tableRow': 5,
        'tableColumn': 4,
        'spiralRow': 6,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 2},
            '5': { 's': 2 }
        },
        'atomicMass': 91.224,
        'metallic': 'metal',
        '1stIonizationEnergy': 640.1,
        'electronAffinity': 41.806,
        'meltingPoint': 1852,
        'boilingPoint': 4377,
        'state': 'solid',
        'density': 6.52,
    },
    '41': {
        'symbol': 'Nb',
        'atomicNumber': 41,
        'family': 5,
        'name': 'Niobium',
        "japaneseName": "ニオブ",
        'radius': 1.98,
        'tableRow': 5,
        'tableColumn': 5,
        'spiralRow': 6,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 4},
            '5': { 's': 1 }
        },
        'atomicMass': 92.90638,
        'metallic': 'metal',
        '1stIonizationEnergy': 652.1,
        'electronAffinity': 88.516,
        'meltingPoint': 2477,
        'boilingPoint': 4744,
        'state': 'solid',
        'density': 8.57,
    },
    '42': {
        'symbol': 'Mo',
        'atomicNumber': 42,
        'family': 6,
        'name': 'Molybdenum',
        "japaneseName": "モリブデン",
        'radius': 1.90,
        'tableRow': 5,
        'tableColumn': 6,
        'spiralRow': 6,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 5},
            '5': { 's': 1 }
        },
        'atomicMass': 95.96,
        'metallic': 'metal',
        '1stIonizationEnergy': 684.3,
        'electronAffinity': 72.097,
        'meltingPoint': 2623,
        'boilingPoint': 4639,
        'state': 'solid',
        'density': 10.22,
    },
    '43': {
        'symbol': 'Tc',
        'atomicNumber': 43,
        'family': 7,
        'name': 'Technetium',
        "japaneseName": "テクネチウム",
        'radius': 1.83,
        'tableRow': 5,
        'tableColumn': 7,
        'spiralRow': 6,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 5},
            '5': { 's': 2 }
        },
        'atomicMass': 98,
        'metallic': 'metal',
        '1stIonizationEnergy': 702,
        'electronAffinity': 53,
        'meltingPoint': 2157,
        'boilingPoint': 4265,
        'state': 'solid',
        'density': 11,
    },
    '44': {
        'symbol': 'Ru',
        'atomicNumber': 44,
        'family': 8,
        'name': 'Ruthenium',
        //'weight': 101.07,
        "japaneseName": "ルテニウム",
        'tableRow': 5,
        'tableColumn': 8,
        'spiralRow': 6,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 7},
            '5': { 's': 1 }
        },
        'atomicMass': 101.07,
        'metallic': 'metal',
        '1stIonizationEnergy': 710.2,
        'electronAffinity': 100.950,
        'meltingPoint': 2334,
        'boilingPoint': 4150,
        'state': 'solid',
        'density': 12.45,
    },
    '45': {
        'symbol': 'Rh',
        'atomicNumber': 45,
        'family': 9,
        'name': 'Rhodium',
        "japaneseName": "ロジウム",
        'radius': 1.73,
        'tableRow': 5,
        'tableColumn': 9,
        'spiralRow': 6,
        'spiralColumn': 6,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 8},
            '5': { 's': 1 }
        },
        'atomicMass': 102.90550,
        'metallic': 'metal',
        '1stIonizationEnergy': 719.7,
        'electronAffinity': 110.27,
        'meltingPoint': 1964,
        'boilingPoint': 3695,
        'state': 'solid',
        'density': 12.41,
    },
    '46': {
        'symbol': 'Pd',
        'atomicNumber': 46,
        'family': 10,
        'name': 'Palladium',
        "japaneseName": "パラジウム",
        'radius': 1.69,
        'tableRow': 5,
        'tableColumn': 10,
        'spiralRow': 6,
        'spiralColumn': 7,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
        },
        'atomicMass': 106.42,
        'metallic': 'metal',
        '1stIonizationEnergy': 804.4,
        'electronAffinity': 54.24,
        'meltingPoint': 1554.9,
        'boilingPoint': 2963,
        'state': 'solid',
        'density': 12.023,
    },
    '47': {
        'symbol': 'Ag',
        'atomicNumber': 47,
        'family': 11,
        'name': 'Silver',
        "japaneseName": "銀",
        'radius': 1.65,
        'tableRow': 5,
        'tableColumn': 11,
        'spiralRow': 6,
        'spiralColumn': 8,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 1 }
        },
        'atomicMass': 107.8682,
        'metallic': 'metal',
        '1stIonizationEnergy': 731,
        'electronAffinity': 125.862,
        'meltingPoint': 961.78,
        'boilingPoint': 2162,
        'state': 'solid',
        'density': 10.49,
    },
    '48': {
        'symbol': 'Cd',
        'atomicNumber': 48,
        'family': 12,
        'name': 'Cadmium',
        "japaneseName": "カドミウム",
        'radius': 1.61,
        'tableRow': 5,
        'tableColumn': 12,
        'spiralRow': 6,
        'spiralColumn': 9,
        'winding': 0,
        'orbit': '4d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2 }
        },
        'atomicMass': 112.411,
        'metallic': 'metal',
        '1stIonizationEnergy': 867.8,
        'electronAffinity': -68,
        'meltingPoint': 321.07,
        'boilingPoint': 767,
        'state': 'solid',
        'density': 8.65,
    },
    '49': {
        'symbol': 'In',
        'atomicNumber': 49,
        'family': 13,
        'name': 'Indium',
        "japaneseName": "インジウム",
        'radius': 1.56,
        'tableRow': 5,
        'tableColumn': 13,
        'spiralRow': 6,
        'spiralColumn': 10,
        'winding': 1,
        'orbit': '5p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 1 }
        },
        'atomicMass': 114.818,
        'metallic': 'metal',
        '1stIonizationEnergy': 558.3,
        'electronAffinity': 37.043,
        'meltingPoint': 156.60,
        'boilingPoint': 2072,
        'state': 'solid',
        'density': 7.31,
    },
    '50': {
        'symbol': 'Sn',
        'atomicNumber': 50,
        'family': 14,
        'name': 'Tin',
        "japaneseName": "スズ",
        'radius': 1.45,
        'tableRow': 5,
        'tableColumn': 14,
        'spiralRow': 7,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '5p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 2 }
        },
        'atomicMass': 118.710,
        'metallic': 'metal',
        '1stIonizationEnergy': 708.6,
        'electronAffinity': 107.298,
        'meltingPoint': 231.93,
        'boilingPoint': 2602,
        'state': 'solid',
        'density': 7.265, //β-Sn
    },
    '51': {
        'symbol': 'Sb',
        'atomicNumber': 51,
        'family': 15,
        'name': 'Antimony',
        "japaneseName": "アンチモン",
        'radius': 1.33,
        'tableRow': 5,
        'tableColumn': 15,
        'spiralRow': 7,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '5p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 3 }
        },
        'atomicMass': 121.760,
        'metallic': 'semimetal',
        '1stIonizationEnergy': 834,
        'electronAffinity': 101.059,
        'meltingPoint': 630.63,
        'boilingPoint': 1635,
        'state': 'solid',
        'density': 6.697,
    },

    '52': {
        'symbol': 'Te',
        'atomicNumber': 52,
        'family': 16,
        'name': 'Tellurium',
        "japaneseName": "テルル",
        'radius': 1.23,
        'tableRow': 5,
        'tableColumn': 16,
        'spiralRow': 7,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '5p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 4 }
        },
        'atomicMass': 127.60,
        'metallic': 'semimetal',
        '1stIonizationEnergy': 869.3,
        'electronAffinity': 190.161,
        'meltingPoint': 449.51,
        'boilingPoint': 988,
        'state': 'solid',
        'density': 6.24,
    },
    '53': {
        'symbol': 'I',
        'atomicNumber': 53,
        'family': 17,
        'name': 'Iodine',
        "japaneseName": "ヨウ素",
        'radius': 1.15,
        'tableRow': 5,
        'tableColumn': 17,
        'spiralRow': 7,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '5p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 5 }
        },
        'atomicMass': 126.90447,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1008.4,
        'electronAffinity': 295.153,
        'meltingPoint': 113.7,
        'boilingPoint': 184.3,
        'state': 'solid',
        'density': 4.93,
    },
    '54': {
        'symbol': 'Xe',
        'atomicNumber': 54,
        'family': 18,
        'name': 'Xenon',
        "japaneseName": "キセノン",
        'radius': 1.08,
        'tableRow': 5,
        'tableColumn': 18,
        'spiralRow': 7,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '5p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 6 }
        },
        'atomicMass': 131.293,
        'metallic': 'nonmetal',
        '1stIonizationEnergy': 1170.4,
        'electronAffinity': -77,
        'meltingPoint': -111.75,
        'boilingPoint': -108.099,
        'state': 'gas',
        'density': 0.005887,
    },
    '55': {
        'symbol': 'Cs',
        'atomicNumber': 55,
        'family': 1,
        'name': 'Cesium',
        "japaneseName": "セシウム",
        'radius': 2.98,
        'tableRow': 6,
        'tableColumn': 1,
        'spiralRow': 7,
        'spiralColumn': 6,
        'winding': 1,
        'orbit': '6s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 6},
            '6': { 's': 1 }
        },
        'atomicMass': 132.9054519,
        'metallic': 'metal',
        '1stIonizationEnergy': 375.7,
        'electronAffinity': 45.505,
        'meltingPoint': 28.5,
        'boilingPoint': 671,
        'state': 'solid',
        'density': 1.93,
    },
    '56': {
        'symbol': 'Ba',
        'atomicNumber': 56,
        'family': 2,
        'name': 'Barium',
        "japaneseName": "バリウム",
        'radius': 2.53,
        'tableRow': 6,
        'tableColumn': 2,
        'spiralRow': 7,
        'spiralColumn': 7,
        'winding': 1,
        'orbit': '6s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 6},
            '6': { 's': 2 }
        },
        'atomicMass': 137.327,
        'metallic': 'metal',
        '1stIonizationEnergy': 502.9,
        'electronAffinity': 13.954,
        'meltingPoint': 727,
        'boilingPoint': 1845,
        'state': 'solid',
        'density': 3.51,
    },
    '57': {
        'symbol': 'La',
        'atomicNumber': 57,
        'family': 3,
        'name': 'Lanthanum',
        "japaneseName": "ランタン",
        'radius': 2.07,
        'tableRow': 9,
        'tableColumn': 3,
        'spiralRow': 7,
        'spiralColumn': 8,
        'winding': 2,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10},
            '5': { 's': 2, 'p': 6, 'd': 1},
            '6': { 's': 2},
        },
        'atomicMass': 138.90547,
        'metallic': 'metal',
        '1stIonizationEnergy': 538.1,
        'electronAffinity': 53.795,
        'meltingPoint': 920,
        'boilingPoint': 3464,
        'state': 'solid',
        'density': 6.162,
    },
    '58': {
        'symbol': 'Ce',
        'atomicNumber': 58,
        'family': 3,
        'name': 'Cerium',
        "japaneseName": "セリウム",
        'radius': 2.04,
        'tableRow': 9,
        'tableColumn': 4,
        'spiralRow': 8,
        'spiralColumn': 1,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 1},
            '5': { 's': 2, 'p': 6, 'd': 1},
            '6': { 's': 2},
        },
        'atomicMass': 140.116,
        'metallic': 'metal',
        '1stIonizationEnergy': 534.4,
        'electronAffinity': 57.906,
        'meltingPoint': 795,
        'boilingPoint': 3443,
        'state': 'solid',
        'density': 6.77,
    },
    '59': {
        'symbol': 'Pr',
        'atomicNumber': 59,
        'family': 3,
        'name': 'Praseodymium',
        "japaneseName": "プラセオジム",
        'radius': 2.03,
        'tableRow': 9,
        'tableColumn': 5,
        'spiralRow': 8,
        'spiralColumn': 2,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 3},
            '5': { 's': 2, 'p': 6},
            '6': { 's': 2},
        },
        'atomicMass': 140.90765,
        'metallic': 'metal',
        '1stIonizationEnergy': 527,
        'electronAffinity': 10.539,
        'meltingPoint': 935,
        'boilingPoint': 3130,
        'state': 'solid',
        'density': 6.77,
    },
    '60': {
        'symbol': 'Nd',
        'atomicNumber': 60,
        'family': 3,
        'name': 'Neodymium',
        "japaneseName": "ネオジム",
        'radius': 2.01,
        'tableRow': 9,
        'tableColumn': 6,
        'spiralRow': 8,
        'spiralColumn': 3,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 4},
            '5': { 's': 2, 'p': 6},
            '6': { 's': 2},
        },
        'atomicMass': 144.242,
        'metallic': 'metal',
        '1stIonizationEnergy': 533.1,
        'electronAffinity': 9.406,
        'meltingPoint': 1024,
        'boilingPoint': 3074,
        'state': 'solid',
        'density': 7.01,
    },
    '61': {
        'symbol': 'Pm',
        'atomicNumber': 61,
        'family': 3,
        'name': 'Promethium',
        "japaneseName": "プロメチウム",
        'radius': 1.99,
        'tableRow': 9,
        'tableColumn': 7,
        'spiralRow': 8,
        'spiralColumn': 4,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 5 },
            '5': { 's': 2, 'p': 6 },
            '6': { 's': 2 }
        },
        'atomicMass': 145,
        'metallic': 'metal',
        '1stIonizationEnergy': 540,
        'electronAffinity': 12.45,
        'meltingPoint': 1042,
        'boilingPoint': 3000,
        'state': 'solid',
        'density': 7.26,
    },
    '62': {
        'symbol': 'Sm',
        'atomicNumber': 62,
        'family': 3,
        'name': 'Samarium',
        "japaneseName": "サマリウム",
        'radius': 1.98,
        'tableRow': 9,
        'tableColumn': 8,
        'spiralRow': 8,
        'spiralColumn': 5,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 6 },
            '5': { 's': 2, 'p': 6 },
            '6': { 's': 2 }
        },
        'atomicMass': 150.36,
        'metallic': 'metal',
        '1stIonizationEnergy': 544.5,
        'electronAffinity': 15.63, //ここまで
        'meltingPoint': 1072,
        'boilingPoint': 1900,
        'state': 'solid',
        'density': 7.52,

    },
    '63': {
        'symbol': 'Eu',
        'atomicNumber': 63,
        'family': 3,
        'name': 'Europium',
        "japaneseName": "ユーロピウム",
        'radius': 1.98,
        'tableRow': 9,
        'tableColumn': 9,
        'spiralRow': 8,
        'spiralColumn': 6,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 7 },
            '5': { 's': 2, 'p': 6 },
            '6': { 's': 2 }
        },
        'atomicMass': 151.964,
        'metallic': 'metal',
        '1stIonizationEnergy': 547.1,
        'electronAffinity': 11.2,
        'meltingPoint': 826,
        'boilingPoint': 1529,
        'state': 'solid',
        'density': 5.244,
    },
    '64': {
        'symbol': 'Gd',
        'atomicNumber': 64,
        'family': 3,
        'name': 'Gadolinium',
        "japaneseName": "ガドリニウム",
        'radius': 1.96,
        'tableRow': 9,
        'tableColumn': 10,
        'spiralRow': 8,
        'spiralColumn': 7,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 7 },
            '5': { 's': 2, 'p': 6, 'd': 1 },
            '6': { 's': 2 }
        },
        'atomicMass': 157.25,
        'metallic': 'metal',
        '1stIonizationEnergy': 593.4,
        'electronAffinity': 20.5,
        'meltingPoint': 1312,
        'boilingPoint': 3273,
        'state': 'solid',
        'density': 7.90,
    },
    '65': {
        'symbol': 'Tb',
        'atomicNumber': 65,
        'family': 3,
        'name': 'Terbium',
        "japaneseName": "テルビウム",
        'radius': 1.94,
        'tableRow': 9,
        'tableColumn': 11,
        'spiralRow': 8,
        'spiralColumn': 8,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 9 },
            '5': { 's': 2, 'p': 6 },
            '6': { 's': 2 }
        },
        'atomicMass': 158.92535,
        'metallic': 'metal',
        '1stIonizationEnergy': 565.8,
        'electronAffinity': 12.670,
        'meltingPoint': 1356,
        'boilingPoint': 3123,
        'state': 'solid',
        'density': 8.23,
    },
    '66': {
        'symbol': 'Dy',
        'atomicNumber': 66,
        'family': 3,
        'name': 'Dysprosium',
        "japaneseName": "ジスプロシウム",
        'radius': 1.92,
        'tableRow': 9,
        'tableColumn': 12,
        'spiralRow': 8,
        'spiralColumn': 9,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 10 },
            '5': { 's': 2, 'p': 6 },
            '6': { 's': 2 }
        },
        'atomicMass': 162.500,
        'metallic': 'metal',
        '1stIonizationEnergy': 573,
        'electronAffinity': 1.45,
        'meltingPoint': 1407,
        'boilingPoint': 2562,
        'state': 'solid',
        'density': 8.540,
    },
    '67': {
        'symbol': 'Ho',
        'atomicNumber': 67,
        'family': 3,
        'name': 'Holmium',
        "japaneseName": "ホルミウム",
        'radius': 1.92,
        'tableRow': 9,
        'tableColumn': 13,
        'spiralRow': 8,
        'spiralColumn': 10,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 11 },
            '5': { 's': 2, 'p': 6 },
            '6': { 's': 2 }
        },
        'atomicMass': 164.93032,
        'metallic': 'metal',
        '1stIonizationEnergy': 581,
        'electronAffinity': 32.61,
        'meltingPoint': 1461,
        'boilingPoint': 2600,
        'state': 'solid',
        'density': 8.79,
    },
    '68': {
        'symbol': 'Er',
        'atomicNumber': 68,
        'family': 3,
        'name': 'Erbium',
        "japaneseName": "エルビウム",
        'radius': 1.89,
        'tableRow': 9,
        'tableColumn': 14,
        'spiralRow': 8,
        'spiralColumn': 11,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 12 },
            '5': { 's': 2, 'p': 6 },
            '6': { 's': 2 }
        },
        'atomicMass': 167.259,
        'metallic': 'metal',
        '1stIonizationEnergy': 589.3,
        'electronAffinity': 30.10,
        'meltingPoint': 1529,
        'boilingPoint': 2868,
        'state': 'solid',
        'density': 9.066,
    },
    '69': {
        'symbol': 'Tm',
        'atomicNumber': 69,
        'family': 3,
        'name': 'Thulium',
        "japaneseName": "ツリウム",
        'radius': 1.90,
        'tableRow': 9,
        'tableColumn': 15,
        'spiralRow': 8,
        'spiralColumn': 12,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 13},
            '5': { 's': 2, 'p': 6},
            '6': { 's': 2}
        },
        'atomicMass': 168.93421,
        'metallic': 'metal',
        '1stIonizationEnergy': 596.7,
        'electronAffinity': 99,
        'meltingPoint': 1545,
        'boilingPoint': 1950,
        'state': 'solid',
        'density': 9.32,
    },
    '70': {
        'symbol': 'Yb',
        'atomicNumber': 70,
        'family': 3,
        'name': 'Ytterbium',
        "japaneseName": "イッテルビウム",
        'radius': 1.87,
        'tableRow': 9,
        'tableColumn': 16,
        'spiralRow': 8,
        'spiralColumn': 13,
        'winding': 1,
        'orbit': '4f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6},
            '6': { 's': 2}
        },
        'atomicMass': 173.054,
        'metallic': 'metal',
        '1stIonizationEnergy': 603.4,
        'electronAffinity': -1.93,
        'meltingPoint': 824,
        'boilingPoint': 1196,
        'state': 'solid',
        'density': 6.90,
    },
    '71': {
        'symbol': 'Lu',
        'atomicNumber': 71,
        'family': 3,
        'name': 'Lutetium',
        "japaneseName": "ルテチウム",
        'radius': 1.87,
        'tableRow': 9,
        'tableColumn': 17,
        'spiralRow': 8,
        'spiralColumn': 14,
        'winding': 1,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 1},
            '6': { 's': 2}
        },
        'atomicMass': 174.9668,
        'metallic': 'metal',
        '1stIonizationEnergy': 523.5,
        'electronAffinity': 23.04,
        'meltingPoint': 1652,
        'boilingPoint': 3402,
        'state': 'solid',
        'density': 9.841,
    },
    '72': {
        'symbol': 'Hf',
        'atomicNumber': 72,
        'family': 4,
        'name': 'Hafnium',
        "japaneseName": "ハフニウム",
        'radius': 1.75,
        'tableRow': 6,
        'tableColumn': 4,
        'spiralRow': 9,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 2},
            '6': { 's': 2}
        },
        'atomicMass': 178.49,
        'metallic': 'metal',
        '1stIonizationEnergy': 658.5,
        'electronAffinity': 17.18,
        'meltingPoint': 2233,
        'boilingPoint': 4603,
        'state': 'solid',
        'density': 13.31,
    },
    '73': {
        'symbol': 'Ta',
        'atomicNumber': 73,
        'family': 5,
        'name': 'Tantalum',
        "japaneseName": "タンタル",
        'radius': 1.70,
        'tableRow': 6,
        'tableColumn': 5,
        'spiralRow': 9,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 3},
            '6': { 's': 2}
        },
        'atomicMass': 180.94788,
        'metallic': 'metal',
        '1stIonizationEnergy': 761,
        'electronAffinity': 31.730,
        'meltingPoint': 3017,
        'boilingPoint': 5458,
        'state': 'solid',
        'density': 16.69,

    },
    '74': {
        'symbol': 'W',
        'atomicNumber': 74,
        'family': 6,
        'name': 'Tungsten',
        "japaneseName": "タングステン",
        'radius': 1.62,
        'tableRow': 6,
        'tableColumn': 6,
        'spiralRow': 9,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 4},
            '6': { 's': 2}
        },
        'atomicMass': 183.84,
        'metallic': 'metal',
        '1stIonizationEnergy': 770,
        'electronAffinity': 78.76,
        'meltingPoint': 3422,
        'boilingPoint': 5930,
        'state': 'solid',
        'density': 19.25,
    },
    '75': {
        'symbol': 'Re',
        'atomicNumber': 75,
        'family': 7,
        'name': 'Rhenium',
        "japaneseName": "レニウム",
        'radius': 1.51,
        'tableRow': 6,
        'tableColumn': 7,
        'spiralRow': 9,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 5},
            '6': { 's': 2}
        },
        'atomicMass': 186.207,
        'metallic': 'metal',
        '1stIonizationEnergy': 760,
        'electronAffinity': 5.827,
        'meltingPoint': 3186,
        'boilingPoint': 5630,
        'state': 'solid',
        'density': 21.02,
    },
    '76': {
        'symbol': 'Os',
        'atomicNumber': 76,
        'family': 8,
        'name': 'Osmium',
        "japaneseName": "オスミウム",
        'radius': 1.44,
        'tableRow': 6,
        'tableColumn': 8,
        'spiralRow': 9,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 6},
            '6': { 's': 2}
        },
        'atomicMass': 190.23,
        'metallic': 'metal',
        '1stIonizationEnergy': 840,
        'electronAffinity': 103.978,
        'meltingPoint': 3033,
        'boilingPoint': 5012,
        'state': 'solid',
        'density': 22.59,
    },
    '77': {
        'symbol': 'Ir',
        'atomicNumber': 77,
        'family': 9,
        'name': 'Iridium',
        "japaneseName": "イリジウム",
        'radius': 1.41,
        'tableRow': 6,
        'tableColumn': 9,
        'spiralRow': 9,
        'spiralColumn': 6,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 7},
            '6': { 's': 2}
        },
        'atomicMass': 192.217,
        'metallic': 'metal',
        '1stIonizationEnergy': 880,
        'electronAffinity': 150.908,
        'meltingPoint': 2446,
        'boilingPoint': 4130,
        'state': 'solid',
        'density': 22.56,
    },
    '78': {
        'symbol': 'Pt',
        'atomicNumber': 78,
        'family': 10,
        'name': 'Platinum',
        "japaneseName": "プラチナ",
        'radius': 1.36,
        'tableRow': 6,
        'tableColumn': 10,
        'spiralRow': 9,
        'spiralColumn': 7,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 9},
            '6': { 's': 1}
        },
        'atomicMass': 195.084,
        'metallic': 'metal',
        '1stIonizationEnergy': 870,
        'electronAffinity': 205.041,
        'meltingPoint': 1768.3,
        'boilingPoint': 3825,
        'state': 'solid',
        'density': 21.45,
    },
    '79': {
        'symbol': 'Au',
        'atomicNumber': 79,
        'family': 11,
        'name': 'Gold',
        "japaneseName": "ゴールド",
        'radius': 1.36,
        'tableRow': 6,
        'tableColumn': 11,
        'spiralRow': 9,
        'spiralColumn': 8,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 1 }
        },
        'atomicMass': 196.966569,
        'metallic': 'metal',
        '1stIonizationEnergy': 890.1,
        'electronAffinity': 222.747,
        'meltingPoint': 1064.18,
        'boilingPoint': 2970,
        'state': 'solid',
        'density': 19.3,
    },
    '80': {
        'symbol': 'Hg',
        'atomicNumber': 80,
        'family': 12,
        'name': 'Mercury',
        "japaneseName": "水銀",
        'radius': 1.32,
        'tableRow': 6,
        'tableColumn': 12,
        'spiralRow': 9,
        'spiralColumn': 9,
        'winding': 0,
        'orbit': '5d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2 }
        },
        'atomicMass': 200.59,
        'metallic': 'metal',
        '1stIonizationEnergy': 1007.1,
        'electronAffinity': -48,
        'meltingPoint': -38.8290,
        'boilingPoint': 356.73,
        'state': 'liquid',
        'density': 13.546,
    },
    '81': {
        'symbol': 'Tl',
        'atomicNumber': 81,
        'family': 13,
        'name': 'Thallium',
        "japaneseName": "タリウム",
        'radius': 1.45,
        'tableRow': 6,
        'tableColumn': 13,
        'spiralRow': 9,
        'spiralColumn': 10,
        'winding': 1,
        'orbit': '6p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 1 }
        },
        'atomicMass': 204.3833,
        'metallic': 'metal',
        '1stIonizationEnergy': 589.4,
        'electronAffinity': 30.880,
        'meltingPoint': 304,
        'boilingPoint': 1473,
        'state': 'solid',
        'density': 11.85,
    },
    '82': {
        'symbol': 'Pb',
        'atomicNumber': 82,
        'family': 14,
        'name': 'Lead',
        "japaneseName": "鉛",
        'radius': 1.46,
        'tableRow': 6,
        'tableColumn': 14,
        'spiralRow': 10,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '6p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 2 }
        },
        'atomicMass': 207.2,
        'metallic': 'metal',
        '1stIonizationEnergy': 715.6,
        'electronAffinity': 34.418,
        'meltingPoint': 327.46,
        'boilingPoint': 1749,
        'state': 'solid',
        'density': 11.34,
    },
    '83': {
        'symbol': 'Bi',
        'atomicNumber': 83,
        'family': 15,
        'name': 'Bismuth',
        "japaneseName": "ビスマス",
        'radius': 1.48,
        'tableRow': 6,
        'tableColumn': 15,
        'spiralRow': 10,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '6p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 3 }
        },
        'atomicMass': 208.98040,
        'metallic': 'metal',
        '1stIonizationEnergy': 703,
        'electronAffinity': 90.924,
        'meltingPoint': 271.5,
        'boilingPoint': 1564,
        'state': 'solid',
        'density': 9.78,
    },
    '84': {
        'symbol': 'Po',
        'atomicNumber': 84,
        'family': 16,
        'name': 'Polonium',
        "japaneseName": "ポロニウム",
        'radius': 1.40,
        'tableRow': 6,
        'tableColumn': 16,
        'spiralRow': 10,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '6p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 4 }
        },
        'atomicMass': 209,
        'metallic': 'metal',
        '1stIonizationEnergy': 812.1,
        'electronAffinity': 136,
        'meltingPoint': 254,
        'boilingPoint': 962,
        'state': 'solid',
        'density': 9.196,
    },
    '85': {
        'symbol': 'At',
        'atomicNumber': 85,
        'family': 17,
        'name': 'Astatine',
        "japaneseName": "アスタチン",
        'radius': 1.50,
        'tableRow': 6,
        'tableColumn': 17,
        'spiralRow': 10,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '6p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 5 }
        },
        'atomicMass': 210,
        'metallic': 'metal',
        '1stIonizationEnergy': 899.003,
        'electronAffinity': 233.087,
        'meltingPoint': null,
        'boilingPoint': null,
        'state': 'solid',
        'density': 8.93,
    },

    '86': {
        'symbol': 'Rn',
        'atomicNumber': 86,
        'family': 18,
        'name': 'Radon',
        "japaneseName": "ラドン",
        'radius': 1.50,
        'tableRow': 6,
        'tableColumn': 18,
        'spiralRow': 10,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '6p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 6 }
        },
        'atomicMass': 222,
        'metallic': 'metal',
        '1stIonizationEnergy': 1037,
        'electronAffinity': -68,
        'meltingPoint': -71,
        'boilingPoint': -61.7,
        'state': 'gas',
        'density': 0.00973,
    },
    '87': {
        'symbol': 'Fr',
        'atomicNumber': 87,
        'family': 1,
        'name': 'Francium',
        "japaneseName": "フランシウム",
        'radius': 2.60,
        'tableRow': 7,
        'tableColumn': 1,
        'spiralRow': 10,
        'spiralColumn': 6,
        'winding': 1,
        'orbit': '7s',
        'electron': {
            '1': { 's': 1 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 6 },
            '7': { 's': 1 }
        },
        'atomicMass': 223,
        'metallic': 'metal',
        '1stIonizationEnergy': 380,
        'electronAffinity': 46.89,
        'meltingPoint': 27,
        'boilingPoint': 677,
        'state': 'solid',
        'density': 2.48,
    },
    '88': {
        'symbol': 'Ra',
        'atomicNumber': 88,
        'family': 2,
        'name': 'Radium',
        "japaneseName": "ラジウム",
        'radius': 2.21,
        'tableRow': 7,
        'tableColumn': 2,
        'spiralRow': 10,
        'spiralColumn': 7,
        'winding': 1,
        'orbit': '7s',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 6 },
            '7': { 's': 2 }
        },
        'atomicMass': 226,
        'metallic': 'metal',
        '1stIonizationEnergy': 509.3,
        'electronAffinity': 9.648,
        'meltingPoint': 700,
        'boilingPoint': 1737,
        'state': 'solid',
        'density': 5.5,
    },
    '89': {
        'symbol': 'Ac',
        'atomicNumber': 89,
        'family': 3,
        'name': 'Actinium',
        "japaneseName": "アクチニウム",
        'radius': 2.15,
        'tableRow': 10,
        'tableColumn': 3,
        'spiralRow': 10,
        'spiralColumn': 8,
        'winding': 2,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 6, 'd': 1 },
            '7': { 's': 2 }
        },
        'atomicMass': 227,
        'metallic': 'metal',
        '1stIonizationEnergy': 499,
        'electronAffinity': 33.77,
        'meltingPoint': 1227,
        'boilingPoint': 3200,
        'state': 'solid',
        'density': 10,
    },
    '90': {
        'symbol': 'Th',
        'atomicNumber': 90,
        'family': 3,
        'name': 'Thorium',
        "japaneseName": "トリウム",
        'radius': 2.06,
        'tableRow': 10,
        'tableColumn': 4,
        'spiralRow': 11,
        'spiralColumn': 1,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10 },
            '6': { 's': 2, 'p': 6, 'd': 2 },
            '7': { 's': 2 }
        },
        'atomicMass': 232.03806,
        'metallic': 'metal',
        '1stIonizationEnergy': 587,
        'electronAffinity': 58.633,
        'meltingPoint': 1750,
        'boilingPoint': 4788,
        'state': 'solid',
        'density': 11.7,
    },
    '91': {
        'symbol': 'Pa',
        'atomicNumber': 91,
        'family': 3,
        'name': 'Protactinium',
        "japaneseName": "プロトアクチニウム",
        'radius': 2.00,
        'tableRow': 10,
        'tableColumn': 5,
        'spiralRow': 11,
        'spiralColumn': 2,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 2 },
            '6': { 's': 2, 'p': 6, 'd': 1 },
            '7': { 's': 2 }
        },
        'atomicMass': 231.03588,
        'metallic': 'metal',
        '1stIonizationEnergy': 568,
        'electronAffinity': 53.03,
        'meltingPoint': 1568,
        'boilingPoint': 4027,
        'state': 'solid',
        'density': 15.37,
    },
    '92': {
        'symbol': 'U',
        'atomicNumber': 92,
        'family': 3,
        'name': 'Uranium',
        "japaneseName": "ウラン",
        'radius': 1.96,
        'tableRow': 10,
        'tableColumn': 6,
        'spiralRow': 11,
        'spiralColumn': 3,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 3 },
            '6': { 's': 2, 'p': 6, 'd': 1 },
            '7': { 's': 2 }
        },
        'atomicMass': 238.02891,
        'metallic': 'metal',
        '1stIonizationEnergy': 597.6,
        'electronAffinity': 30.390,
        'meltingPoint': 1132.2,
        'boilingPoint': 4131,
        'state': 'solid',
        'density': 19.1,
    },
    '93': {
        'symbol': 'Np',
        'atomicNumber': 93,
        'family': 3,
        'name': 'Neptunium',
        "japaneseName": "ネプツニウム",
        'radius': 1.90,
        'tableRow': 10,
        'tableColumn': 7,
        'spiralRow': 11,
        'spiralColumn': 4,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 4},
            '6': { 's': 2, 'p': 6, 'd': 1},
            '7': { 's': 2}
        },
        'atomicMass': 237,
        'metallic': 'metal',
        '1stIonizationEnergy': 604.5,
        'electronAffinity': 45.85,
        'meltingPoint': 639,
        'boilingPoint': 4174,
        'state': 'solid',
        'density': 20.45,
    },
    '94': {
        'symbol': 'Pu',
        'atomicNumber': 94,
        'family': 3,
        'name': 'Plutonium',
        "japaneseName": "プルトニウム",
        'radius': 1.87,
        'tableRow': 10,
        'tableColumn': 8,
        'spiralRow': 11,
        'spiralColumn': 5,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 6},
            '6': { 's': 2, 'p': 6},
            '7': { 's': 2}
        },
        'atomicMass': 239,
        'metallic': 'metal',
        '1stIonizationEnergy': 585,
        'electronAffinity': -48.33,
        'meltingPoint': 639.4,
        'boilingPoint': 3228,
        'state': 'solid',
        'density': 19.85,
    },
    '95': {
        'symbol': 'Am',
        'atomicNumber': 95,
        'family': 3,
        'name': 'Americium',
        "japaneseName": "アメリシウム",
        'radius': 1.80,
        'tableRow': 10,
        'tableColumn': 9,
        'spiralRow': 11,
        'spiralColumn': 6,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 7},
            '6': { 's': 2, 'p': 6},
            '7': { 's': 2}
        },
        'atomicMass': 243,
        'metallic': 'metal',
        '1stIonizationEnergy': 578,
        'electronAffinity': 9.93,
        'meltingPoint': 1176,
        'boilingPoint': 2607,
        'state': 'solid',
        'density': 12,
    },
    '96': {
        'symbol': 'Cm',
        'atomicNumber': 96,
        'family': 3,
        'name': 'Curium',
        "japaneseName": "キュリウム",
        'radius': 1.69,
        'tableRow': 10,
        'tableColumn': 10,
        'spiralRow': 11,
        'spiralColumn': 7,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 7},
            '6': { 's': 2, 'p': 6, 'd': 1},
            '7': { 's': 2}
        },
        'atomicMass': 247,
        'metallic': 'metal',
        '1stIonizationEnergy': 581,
        'electronAffinity': -27.17,
        'meltingPoint': 1340,
        'boilingPoint': 3110,
        'state': 'solid',
        'density': 13.51,
    },
    '97': {
        'symbol': 'Bk',
        'atomicNumber': 97,
        'family': 3,
        'name': 'Berkelium',
        "japaneseName": "バークリウム",
        'radius': 1.70,
        'tableRow': 10,
        'tableColumn': 11,
        'spiralRow': 11,
        'spiralColumn': 8,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 9},
            '6': { 's': 2, 'p': 6},
            '7': { 's': 2}
        },
        'atomicMass': 247,
        'metallic': 'metal',
        '1stIonizationEnergy': 601,
        'electronAffinity': -165.24,
        'meltingPoint': 986,
        'boilingPoint': 2627,
        'state': 'solid',
        'density': 14.78,
    },
    '98': {
        'symbol': 'Cf',
        'atomicNumber': 98,
        'family': 3,
        'name': 'Californium',
        "japaneseName": "カリフォルニウム",
        'radius': 1.86,
        'tableRow': 10,
        'tableColumn': 12,
        'spiralRow': 11,
        'spiralColumn': 9,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 10},
            '6': { 's': 2, 'p': 6},
            '7': { 's': 2}
        },
        'atomicMass': 252,
        'metallic': 'metal',
        '1stIonizationEnergy': 608,
        'electronAffinity': -97.31,
        'meltingPoint': 900,
        'boilingPoint': 1470,
        'state': 'solid',
        'density': 15.1,
    },
    '99': {
        'symbol': 'Es',
        'atomicNumber': 99,
        'family': 3,
        'name': 'Einsteinium',
        "japaneseName": "アインスタイニウム",
        'radius': 1.86,
        'tableRow': 10,
        'tableColumn': 13,
        'spiralRow': 11,
        'spiralColumn': 10,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 11},
            '6': { 's': 2, 'p': 6},
            '7': { 's': 2}
        },
        'atomicMass': 252,
        'metallic': 'metal',
        '1stIonizationEnergy': 619,
        'electronAffinity': -28.60,
        'meltingPoint': 860,
        'boilingPoint': 996,
        'state': 'solid',
        'density': 8.84,
    },
    '100': {
        'symbol': 'Fm',
        'atomicNumber': 100,
        'family': 3,
        'name': 'Fermium',
        "japaneseName": "フェルミウム",
        'radius': 1.86,
        'tableRow': 10,
        'tableColumn': 14,
        'spiralRow': 11,
        'spiralColumn': 11,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 12},
            '6': { 's': 2, 'p': 6},
            '7': { 's': 2}
        },
        'atomicMass': 257,
        'metallic': 'metal',
        '1stIonizationEnergy': 627,
        'electronAffinity': 33.96,
        'meltingPoint': 1500,
        'boilingPoint': null,
        'state': 'solid',
        'density': 9.7,
    },
    '101': {
        'symbol': 'Md',
        'atomicNumber': 101,
        'family': 3,
        'name': 'Mendelevium',
        "japaneseName": "メンデレビウム",
        'radius': 1.86,
        'tableRow': 10,
        'tableColumn': 15,
        'spiralRow': 11,
        'spiralColumn': 12,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 13},
            '6': { 's': 2, 'p': 6},
            '7': { 's': 2}
        },
        'atomicMass': 258,
        'metallic': 'metal',
        '1stIonizationEnergy': 635,
        'electronAffinity': 93.91,
        'meltingPoint': 800,
        'boilingPoint': null,
        'state': 'solid',
        'density': 10.3,
    },
    '102': {
        'symbol': 'No',
        'atomicNumber': 102,
        'family': 3,
        'name': 'Nobelium',
        "japaneseName": "ノーベリウム",
        'radius': 1.86,
        'tableRow': 10,
        'tableColumn': 16,
        'spiralRow': 11,
        'spiralColumn': 13,
        'winding': 1,
        'orbit': '5f',
        'electron': {
            '1': { 's': 2},
            '2': { 's': 2, 'p': 6},
            '3': { 's': 2, 'p': 6, 'd': 10},
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '6': { 's': 2, 'p': 6},
            '7': { 's': 2}
        },
        'atomicMass': 259,
        'metallic': 'metal',
        '1stIonizationEnergy': 642,
        'electronAffinity': null,//-223.22?,
        'meltingPoint': 800,
        'boilingPoint': null,
        'state': 'solid',
        'density': 9.9,
    },
    '103': {
        'symbol': 'Lr',
        'atomicNumber': 103,
        'family': 3,
        'name': 'Lawrencium',
        "japaneseName": "ローレンシウム",
        'radius': 1.86,
        'tableRow': 10,
        'tableColumn': 17,
        'spiralRow': 11,
        'spiralColumn': 14,
        'winding': 1,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6 },
            '7': { 's': 2, 'p': 1 }
        },
        'atomicMass': 262,
        'metallic': 'metal',
        '1stIonizationEnergy': 479,
        'electronAffinity': -30.04,
        'meltingPoint': 1600,
        'boilingPoint': null,
        'state': 'solid',
        'density': 14.4,
    },
    '104': {
        'symbol': 'Rf',
        'atomicNumber': 104,
        'family': 4,
        'name': 'Rutherfordium',
        "japaneseName": "ラザホージウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 4,
        'spiralRow': 12,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 2 },
            '7': { 's': 2}
        },
        'atomicMass': 267,
        'metallic': 'metal',
        '1stIonizationEnergy': 580,
        'electronAffinity': null,
        'meltingPoint': 2100,
        'boilingPoint': 5500,
        'state': 'solid',
        'density': 17,
    },
    '105': {
        'symbol': 'Db',
        'atomicNumber': 105,
        'family': 5,
        'name': 'Dubnium',
        "japaneseName": "ドブニウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 5,
        'spiralRow': 12,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 3 },
            '7': { 's': 2}
        },
        'atomicMass': 268,
        'metallic': 'metal',
        '1stIonizationEnergy': 665,
        'electronAffinity': null,
        'meltingPoint': null,
        'boilingPoint': null,
        'state': 'solid',
        'density': 21.6,
    },
    '106': {
        'symbol': 'Sg',
        'atomicNumber': 106,
        'family': 6,
        'name': 'Seaborgium',
        "japaneseName": "シーボーギウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 6,
        'spiralRow': 12,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 4 },
            '7': { 's': 2}
        },
        'atomicMass': 269,
        'metallic': 'metal',
        '1stIonizationEnergy': 757,
        'electronAffinity': null,
        'meltingPoint': null,
        'boilingPoint': null,
        'state': 'solid',
        'density': 23,
    },

    '107': {
        'symbol': 'Bh',
        'atomicNumber': 107,
        'family': 7,
        'name': 'Bohrium',
        "japaneseName": "ボーリウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 7,
        'spiralRow': 12,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 5 },
            '7': { 's': 2}
        },
        'atomicMass': 270,
        'metallic': 'metal',
        '1stIonizationEnergy': 740,
        'electronAffinity': null,
        'meltingPoint': null,
        'boilingPoint': null,
        'state': 'solid',
        'density': 26,
    },
    '108': {
        'symbol': 'Hs',
        'atomicNumber': 108,
        'family': 8,
        'name': 'Hassium',
        "japaneseName": "ハッシウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 8,
        'spiralRow': 12,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 6 },
            '7': { 's': 2}
        },
        'atomicMass': 277,
        'metallic': 'metal',
        '1stIonizationEnergy': 730,
        'electronAffinity': null,
        'meltingPoint': null,
        'boilingPoint': null,
        'state': 'solid',
        'density': 27,
    },
    '109': {
        'symbol': 'Mt',
        'atomicNumber': 109,
        'family': 9,
        'name': 'Meitnerium',
        "japaneseName": "マイトネリウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 9,
        'spiralRow': 12,
        'spiralColumn': 6,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 7 },
            '7': { 's': 2}
        },
        'atomicMass': 268,
        'metallic': 'metal',
        '1stIonizationEnergy': 800,
        'electronAffinity': null,
        'meltingPoint': null,
        'boilingPoint': null,
        'state': 'solid',
        'density': 27,
    },
    '110': {
        'symbol': 'Ds',
        'atomicNumber': 110,
        'family': 10,
        'name': 'Darmstadtium',
        "japaneseName": "ダームスタチウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 10,
        'spiralRow': 12,
        'spiralColumn': 7,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 9 },
            '7': { 's': 1}
        },
        'atomicMass': 281,
        'metallic': 'metal',
        '1stIonizationEnergy': 960,
        'electronAffinity':  null,
        'meltingPoint': null,
        'boilingPoint': null,
        'state': 'solid',
        'density': 26,
    },
    '111': {
        'symbol': 'Rg',
        'atomicNumber': 111,
        'family': 11,
        'name': 'Roentgenium',
        "japaneseName": "レントゲニウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 11,
        'spiralRow': 12,
        'spiralColumn': 8,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 9},
            '7': { 's': 2}
        },
        'atomicMass': 280,
        'metallic': 'metal',
        '1stIonizationEnergy': 1020,
        'electronAffinity': 151.0,
        'meltingPoint': null,
        'boilingPoint': null,
        'state': 'solid',
        'density': 23,
    },
    '112': {
        'symbol': 'Cn',
        'atomicNumber': 112,
        'family': 12,
        'name': 'Copernicium',
        "japaneseName": "コペルニシウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 12,
        'spiralRow': 12,
        'spiralColumn': 9,
        'winding': 0,
        'orbit': '6d',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 10},
            '7': { 's': 2}
        },
        'atomicMass': 285,
        'metallic': 'metal',
        '1stIonizationEnergy': 1155,
        'electronAffinity': null,
        'meltingPoint': 10,
        'boilingPoint': 67,
        'state': 'solid',
        'density': 14.0,

    },
    '113': {
        'symbol': 'Nh',
        'atomicNumber': 113,
        'family': 13,
        'name': 'Nihonium',
        "japaneseName": "ニホニウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 13,
        'spiralRow': 12,
        'spiralColumn': 10,
        'winding': 1,
        'orbit': '7p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14 },
            '6': { 's': 2, 'p': 6, 'd': 10},
            '7': { 's': 2, 'p': 1}
        },
        'atomicMass': 286,
        'metallic': 'metal',
        '1stIonizationEnergy': 704.9,
        'electronAffinity': 66.6,
        'meltingPoint': 430,
        'boilingPoint': 1130,
        'state': 'solid',
        'density': 16,
    },
    '114': {
        'symbol': 'Fl',
        'atomicNumber': 114,
        'family': 14,
        'name': 'Flerovium',
        "japaneseName": "フレロビウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 14,
        'spiralRow': 13,
        'spiralColumn': 1,
        'winding': 0,
        'orbit': '7p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '6': { 's': 2, 'p': 6, 'd': 10},
            '7': { 's': 2, 'p': 2}
        },
        'atomicMass': 289,
        'metallic': 'metal',
        '1stIonizationEnergy': 832.2,
        'electronAffinity': null,
        'meltingPoint': -73,
        'boilingPoint': 107,
        'state': 'solid',
        'density': 11.4,
    },
    '115': {
        'symbol': 'Mc',
        'atomicNumber': 115,
        'family': 15,
        'name': 'Moscovium',
        "japaneseName": "モスコビウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 15,
        'spiralRow': 13,
        'spiralColumn': 2,
        'winding': 0,
        'orbit': '7p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '6': { 's': 2, 'p': 6, 'd': 10},
            '7': { 's': 2, 'p': 3}
        },
        'atomicMass': 289,
        'metallic': 'metal',
        '1stIonizationEnergy': 538.3,
        'electronAffinity': 35.3,
        'meltingPoint': 400,
        'boilingPoint': 1100,
        'state': 'solid',
        'density': 13.5,
    },
    '116': {
        'symbol': 'Lv',
        'atomicNumber': 116,
        'family': 16,
        'name': 'Livermorium',
        "japaneseName": "リバモリウム",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 16,
        'spiralRow': 13,
        'spiralColumn': 3,
        'winding': 0,
        'orbit': '7p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '6': { 's': 2, 'p': 6, 'd': 10},
            '7': { 's': 2, 'p': 4}
        },
        'atomicMass': 293,
        'metallic': 'metal',
        '1stIonizationEnergy': 663.9,
        'electronAffinity': 74.9,
        'meltingPoint': 436, //364-507
        'boilingPoint': 812, //762-862
        'state': 'gas',
        'density': 12.9,
    },
    '117': {
        'symbol': 'Ts',
        'atomicNumber': 117,
        'family': 17,
        'name': 'Tennessine',
        "japaneseName": "テネシン",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 17,
        'spiralRow': 13,
        'spiralColumn': 4,
        'winding': 0,
        'orbit': '7p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '6': { 's': 2, 'p': 6, 'd': 10},
            '7': { 's': 2, 'p': 5}
        },
        'atomicMass': 294,
        'metallic': 'metal',
        '1stIonizationEnergy': 742.9,
        'electronAffinity': 165.9,
        'meltingPoint': 450,
        'boilingPoint': 610,
        'state': 'gas',
        'density': 7.2,//7.1-7.3
    },
    '118': {
        'symbol': 'Og',
        'atomicNumber': 118,
        'family': 18,
        'name': 'Oganesson',
        "japaneseName": "オガネソン",
        'radius': 1.86,
        'tableRow': 7,
        'tableColumn': 18,
        'spiralRow': 13,
        'spiralColumn': 5,
        'winding': 0,
        'orbit': '7p',
        'electron': {
            '1': { 's': 2 },
            '2': { 's': 2, 'p': 6 },
            '3': { 's': 2, 'p': 6, 'd': 10 },
            '4': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '5': { 's': 2, 'p': 6, 'd': 10, 'f': 14},
            '6': { 's': 2, 'p': 6, 'd': 10},
            '7': { 's': 2, 'p': 6}
        },
        'atomicMass': 294,
        'metallic': 'metal',
        '1stIonizationEnergy': 860,
        'electronAffinity': 7.72,
        'meltingPoint': 52, //52 ± 15 °C,
        'boilingPoint': 177, //177 ± 10 °C,
        'state': 'gas',
        'density': 7.2,
    },
















}

export default elements;
